---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.5.1
  - jruby-9.2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - bundle exec rake test TESTOPTS=-v
